[build]
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/weather/seoul"
  to = "http://today-article.herokuapp.com/weather/seoul"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/korea/infect"
  to = "http://today-article.herokuapp.com/korea/infect"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/naver/ranking"
  to = "http://today-article.herokuapp.com/naver/ranking"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/naver/news"
  to = "http://today-article.herokuapp.com/naver/news"
  status = 200
  force = false
  query = {search = ":search} # apply this rule for /?path=example
  conditions = {Role = ["admin"]}